### ISSUE TITLE
E3: BE implementar perfiles distintos para test, dev y prod

### ISSUE THREAD

**Issue by fran-CICS** [leobz/organize-matches#12]
Spring boot maneja configuraciones distintas dependiendo del ambiente utilizado.

- [x] Que para dev use una base de datos distinta de la productiva
- [x] Que para test use un mongo ad-hoc levantado con docker
- [x] Que para prod levante la conexión al mongo posta
- [ ] Ver manejo de variables de entorno en cada ambiente

**Comment by leobz** [comment]
Hola! Dejo una nota con algunas sugerencias

Para `dev`:
- Mongo levantado con docker dentro del Dockerfile existente (el cual actualmente se invoca al hacer `make prod`).
- Cambiar nombre del comando `make prod` a `make dev`. Esto es debido a que al levantar localmente el entorno, estamos deployando en `modo de desarrollo` y no de produccion. Se levantara en `modo de produccion` cuando se levante en la nube (donde quizas el Dockefile tenga que ser otro distinto, con configuraciones adaptadas especificamente a la solucion de cloud que elijamos)
- Agregar archivo en el backend SpringBoot que contenga credenciales harcodeadas de la DB Mongo (que debe coincidir con las credenciales puestas en el Dockerfile correspondiente) [Ej de nombres: `dev.config` o algun otro que corresponda]
-  El comando `make dev` debe ademas, setear la variable de entorno (Ver seccion `Inicio de aplicacion`) en `"dev"`


Para `prod`:
- El mongo no va en un Dockerfile, hasta que no se sepa como se implementara la persistencia en produccion (Especificamente en el servicio de cloud, que podria ser por ejemplo, una DB Mongo PaaS). Por lo tanto se puede skipear.
- Agregar archivo en el backend SpringBoot que contenga credenciales de la DB Mongo, obtenidas via`VARIABLES DE CONFIGURACION` (que debe coincidir con las credenciales puestas en la solucion de cloud)  [Ej de nombres: `prod.config` o algun otro que corresponda]


Para `test`:
- Opción de usar InMemory Repository
- En caso de usar Mongo para test de integracion (para una solucion mas robusta), se puede optar por un comando `docker run [image_config + image_name]`, ya que no es necesario levantar otras imagenes (frontend) para el testing
- Agregar archivo en el backend SpringBoot que contenga credenciales harcodeadas de la DB Mongo (que debe coincidir con las credenciales puestas en el` docker run XXX` correspondiente) [Ej de nombres: `test.config` o algun otro que corresponda]- 
- Agregar un comando `make test` que levante el docker con `docker run` y setee la variable de entorno (Ver seccion `Inicio de aplicacion`)  en `"test"`

Inicio de aplicacion:
- A la hora de iniciar la aplicacion, se debe leer alguna variable de entorno (ej: ENV , ENVIRONMENT, etc), y segun cual sea,  aplicar las configuraciones del archivo de configuracion que corresponde


---

cc @fran-CICS @fernandofrontera 

Es medio largo, pero cualquier duda/comentario estoy a disposicion. Gracias!
