### ISSUE TITLE
Agregar bibliota de logs

### ISSUE THREAD

**Issue by leobz** [leobz/organize-matches#19]
Ver biblioteca de log que viene con spring boot. Logback.

https://www.baeldung.com/logback

**Comment by leobz** [comment]
Buenas! Actualmente veo que el servidor esta devolviendo status 500, pero el back ni siquiera esta mostrando el crash. Un ejemplo de esto es las validaciones de las fechas. 
 ¿Es posible que se esten encapsulando las excepciones con algun rescue en algun lado? De todas maneras, ese punto de falla es un buen candidato a logs

**Comment by FranCICSo** [comment]
> Buenas! Actualmente veo que el servidor esta devolviendo status 500, pero el back ni siquiera esta mostrando el crash. Un ejemplo de esto es las validaciones de las fechas. ¿Es posible que se esten encapsulando las excepciones con algun rescue en algun lado? De todas maneras, ese punto de falla es un buen candidato a logs

Springboot tiene un handler de errores que te permite agarrar los throw de exepciones de los controllers y podes loguearlo ahí https://www.baeldung.com/exception-handling-for-rest-with-spring

**Comment by leobz** [comment]
MR Relacionado -> https://github.com/leobz/organize-matches/pull/50
