### ISSUE TITLE
E2: FE Registro

### ISSUE THREAD

**Issue by leobz** [leobz/organize-matches#40]

**Comment by juan-nisimura** [comment]
Primer prototipo
![registro pantalla drawio](https://user-images.githubusercontent.com/48994113/189492147-f9fd2a3e-0eff-4563-9bf6-167db454adf3.png)

**Comment by leobz** [comment]
Lo veo bien, solo dos detalles:
- Los textos deberían estar en el mismo idioma (yo los puse en español, por
lo que hay que decidir cuál queda)
- La imagen de fondo si se usa esa, hay que aplicarlas en todas las demás
páginas para que haya concistencia (creo que el fondo no debería cambiar en
cada página)
