### ISSUE TITLE
FE Investigar integración con Telegram

### ISSUE THREAD

**Issue by FranCICSo** [leobz/organize-matches#69]
En base a los siguientes análisis ([Interfaz por commandos](https://github.com/leobz/organize-matches/issues/69#issuecomment-1273900739), [Interfaz por WebApp](https://github.com/leobz/organize-matches/issues/69#issuecomment-1281771021)), se llegó a la siguiente [conclusión](https://github.com/leobz/organize-matches/issues/69#issuecomment-1282612734) de ir por la alternativa de la WebApp

- [x] Investigar cómo implementar un login (¿Telegram conserva cookies? ¿Tiene localstorage? O usar OAuth y validar con el número telefónico del usuario) https://core.telegram.org/bots/webapps
- [x] Hacer algunas pruebas de consumición de la API del backend (quizás hardcodeadas) MVP
- [x] Decidir approach a utilizar

**Comment by leobz** [comment]
# Telegram BOT: Command Interface

## Arquitectura de la comunicación

Metodo de conexion con API de Telegram

- WebHook: 
  - Con el token, seteamos la API de Telegram, para que rediriga todas las request a nuestro backend server.
  - https://www.youtube.com/watch?v=MdPpC4w8yNY
- Conectando el backend server a la API de Telegram via long polling, para recibir las actualizaicones (la API de Telegram recibe las notificaciones del boot, y las redirige respondiendo las resquest del backend)
  - https://core.telegram.org/bots/api#getupdates 

Pasar numero de telefono via Bot:
- https://core.telegram.org/bots/2-0-intro#locations-and-numbers
- https://core.telegram.org/bots/api#keyboardbutton

Telegram Oauth:
- https://core.telegram.org/widgets/login (envia al back userId, y fotos del perfil de la cuenta telagram. Ahi se podria actualizqar algun campo "telegramUserId").


Tutoriales de implementación
- https://www.youtube.com/watch?v=6431O3g2vMk
- https://stackoverflow.com/questions/50490617/can-i-launch-a-telegram-bot-from-a-spring-boot-application
- https://github.com/rubenlagus/TelegramBots

## Posibles Casos de Uso
Dado que la complejidad de el uso mediante commands radica en la Autorizacion de las solicitudes/commands, se propone la siguiente implementación 

### Commandos no autenticados

- **Listar Partidos**: Devuelve el listado de todos los partidos disponibles, con el matchID asociado (para que puedan anotarse luego a dicho partido) **No requiere autenticacion**
- **Metricas de ultimas 2 horas**: Devuelve un mensaje con el resumen. **No requiere autenticacion**

### Comandos autenticados

Se habilitaran despues de hacer **Login**, enviando el numero de teléfono al server. El server asocia (actualiza) el telegramUserID con el usuario que tenga dicho numero de telefono. Luego de esta interacción, se habilitan todas las consultas. Dichas consultas son validadas con el userTelegramID (Va a ser el token de autenticación para los usuarios Telegram)

- **Anotarse a un partido**: Necesita el MatchID
- Por el momento se descarta **Crear un partido** ya que se necesita encontrar una opcion facil de usar que simplifique un formulario y todavia no se encontró



## Investigacion pendiente

- Como definir que el bot  maneje errores (logica de telegram), como por ej ocultar comandos si falla la autenticacion.
- Investigar friendly UI para envio de formulario via comandos
- Analizar si la persistencia de los mensajes que son de 1 dia en la BOT API de Telegram sirven para expirar la sesion.



--- 

# Extra: Custom Telegram BOT API

Telegram BOT API, se puede bajar local. Se debe investigar como setear el bot para apuntar a dicha BOT API local.
- https://github.com/tdlib/telegram-bot-api
- https://tdlib.github.io/telegram-bot-api/build.html?os=Linux

**Comment by leobz** [comment]
Casos de uso UI Telegram

## Opción Interfaz de texto

- Login enviando el numero de teléfono al server. El server asocia (actualiza) el telegramUserID con el usuario que tenga dicho numero de telefono. Luego de esta interacción, se habilitan todas las consultas. Dichas consultas son validadas con el userTelegramID (Va a ser el token de autenticación para los usuarios Telegram)

- Listar Partidos: Devuelve el listado de todos los partidos disponibles, con el matchID asociado (para que puedan anotarse luego a dicho partido)

- Anotarse a un partido (Necesita el MatchID)

- No se puede crear un partido

**Comment by leobz** [comment]
Casos de uso UI Telegram

## Opción Interfaz de texto

- Login enviando el numero de teléfono al server. El server asocia (actualiza) el t

**Comment by leobz** [comment]
Telegram BOT API, se puede bajar local. Ver como setear el bot para apuntar a dicha BOT API local.

Como hace el bot, para manejar errores (por ej de autenticacion)?

Investigar como enviar un formulario

Ver si la persistencia de los mensajes que son de 1 dia en la BOT API de Telegram sirven para expirar la sesion.

**Comment by leobz** [comment]
# Telegram BOT : WebApp

## Deploy de prueba

*Importante:* El servidor esta alojado en mi pc local, por lo que si el bot no funciona es porque mi pc debe estar apagada.

- Abrir Telegram en su celular, y buscar el usuario "matchorganizer"
- Una vez iniciado el bot, si escriben "/" les muestra los comandos disponibles (actualmente solo listar matches)
- Abajo a la izquierda hay un botoncito que dice "WebApp", si lo aprietan les abre la pagina web

## Ventajas
- Es un browser embebido. Tiene LocalStorage, y Cookies.
- Funciona como si fuese una pagina web en el celular
- Cuando se cierra el chat, y se vuelve a abrir. La cookie/localStorage se conservan.
- Cuando se cierra telegram, conserva las cookies/localStorage



## Desventajas
- Se ve muy mal, ya que el sitio no es responsive. Se necesita modificar el sitio para ser apto para celulares 
- Los colores del chat afectan la visibilidad de la pagina significativamente al FONDO de la pagina (actualmente parece ser transparente, por lo que el fondo, es el que se tiene configurado en Telegram). Esto hace que la pagina tenga contrastes feos. Se debe modificar el theme de manera que sea dinamico (La Library de Telegram para JS permite cambiar dichos themes partir del theme de telegram) o estatico (hardcodear un background por default en el CSS)
- No funcionó en Telegram Web (https://web.telegram.org/)


## Importante
- Ajustes > Chats > Navegador en la app (Ver que impacto tiene en la WebApp)
- Al intentar hacer Create Match de manera remota (no desde el localhost, sino con un deploy) [Esto aplica tanto para el browser de Telegram como para Chrome) -> Devuelve 403 `Invalid CORS request`

## Documentacion oficial

- https://core.telegram.org/bots/webapps

---

## Capturas 18/10/2022

Listado de Partidos (Fondo transparente, transluce el de telegram)
![43064cd9-ab03-495b-8bce-b5da3f890807](https://user-images.githubusercontent.com/43507646/196330267-ac60bb33-8a45-41ec-902f-d911866e5d55.jpg)

Listado de Partidos
![c5ab12d9-aa66-45e1-9639-b74431052ca1](https://user-images.githubusercontent.com/43507646/196330282-e0675528-c238-4520-bfd6-ca2d66d8a40e.jpg)

Fallo en creacion de partido (Invalid CORS request)
![78044f72-32d4-40f5-a97f-212789775efd](https://user-images.githubusercontent.com/43507646/196330308-d0266616-e71e-4c94-83fd-94764151b4a3.jpg)

cc  @FranCICSo @fernandofrontera @aleasquini  @SForlizzi @juan-nisimura

**Comment by leobz** [comment]
## Conclusion

El approach más sencillo de implementar a nivel de manejo de sesiones es el de la **WebApp**, ya que reutiliza toda la lógica existente de los JWT + LocalStorage for free.

**Sin embargo**, adaptar la usabilidad a la WebApp implica tener que hacer un diseño responsive suficientemente bueno y que siga los lineamientos de Telegram -> https://core.telegram.org/bots/webapps#designing-web-apps
