### ISSUE TITLE
Modelar dominio para gestionar partidos

### ISSUE THREAD

**Issue by FranCICSo** [leobz/organize-matches#8]
Habría que pensar un poco qué datos van a tener los jugadores, partidos, ¿equipos?, y quién conoce a quién.

Incluir UML en draw.io

**Comment by aleasquini** [comment]
Arranco con algo para que empecemos a creanearlo.

**Partido**
-ID_Partido
-Nombre el partido
-Organizador (**ID_Usuario**)
-Fecha
-Hora
-Lugar(Predio)
-NumeroDeCancha
-JugadoresConfirmadosTitulares (Lista de **JugadorConfirmado**)
-JugadoresConfirmadosSuplentes (Lista de **JugadorConfirmado**)




**Usuario**
-ID_Usuario
-Alias_Usuario
-Nombre Completo
-Telefono
-Mail


**JugadorConfirmado**
-ID_Usuario
-ID_Partido
-HoraConfirmacion




Aclaraciones:
**JugadorConfirmado** tiene -HoraConfirmacion para cumplir con la historia de usuario 4
A **JugadorConfirmado** le puse los ID para hacer los Join, pero lo estoy pensando en un esquema relacional. Quizás puede incluir algunos datos adicionales correspondientes al usuario o partido que podamos necesitar.

**Comment by FranCICSo** [comment]
Después tenemos que pasar todos los atributos a inglés para cumplir la consigna ¿no?
Me parecen copadas algunas propiedades.
Lo único que me parece mejor que en vez de tener un `JugadorConfirmado` podríamos tener simplemente un `Jugador` con propiedades para saber si está confirmado o una lista de partidos donde está confirmado. O bien mapa de id de partido como key y fecha como valor

**Comment by leobz** [comment]
¿Quedaria asi?

**Match**

- id
- name
- User ownerId (ID del creador del partido)
- date
- hour
- location
- courtNumber
- startingPlayers
- substitutePlayers

**Player**

- User user
- LocalDateTime confirmation_dt

**User**
- id
- alias
- fullName
- phone
- email
- password

**Comment by FranCICSo** [comment]
Me parece bien así. 
No entiendo qué es `courtNumber` nomás y el `confirmation_dt` lo pondría con camel case para respetar lo anterior `confirmationDate`.
Después quiero chequear contra el enunciado si el player dentro de una lista de jugadores de un partido debería venir con todos los datos del user, o con el id alcanza

**Comment by leobz** [comment]
Hola, está bien lo del camel case. La otra variable de entorno es lo del
número de cancha pero mepa que está mal la traducción jajaja, modificarla
según se crea conveniente!

**Comment by FranCICSo** [comment]
Ahh, podría ser `playingFieldNumber` como número de campo de juego. Igual capaz court estaba bien, pero no sé tampoco jaja.

**Match**

- id
- name
- User ownerId (ID del creador del partido)
- date
- hour
- location
- playingFieldNumber
- startingPlayers
- substitutePlayers

**Player**

- User user (o sólo userId)
- LocalDateTime confirmationDate

**User**

- id
- alias
- fullName
- phone
- email
- password

**Comment by juan-nisimura** [comment]
Tiro algunos puntos de dudas que me surgieron:
1. En el user story 4 dice "se solicita ver un contador con la cantidad de partidos creados y jugadores anotados en las últimas 2 horas". Acá no sé si nos piden la cantidad de todos los partidos o sólo los creados en las últimas 2 horas. Si es el 2do caso, faltaría agregar un atributo a los partidos con la fecha de creación.
2. En el story 2 dice "Como usuario quiero anotarme a un partido ya creado ingresando mis datos de contacto (teléfono y mail)". Creo que se puede interpretar de dos formas:
-  Cada vez que uno se anota ingresa de nuevo los datos, y estos datos pueden cambiar entre partido y partido.
-  O es único por usuario como está planteado ahora.
3. El playingFieldNumber es discutible, al menos yo creo que está de más. Estaríamos asumiendo que siempre hay un número de cancha y, si lo tuviera, también podría ser parte de location.

Igual, creo que los más importantes son el 1 y el 2. Esos dos se los podemos consultar al ayudante o al profe.

**Comment by FranCICSo** [comment]
> En el user story 4 dice "se solicita ver un contador con la cantidad de partidos creados y jugadores anotados en las últimas 2 horas". Acá no sé si nos piden la cantidad de todos los partidos o sólo los creados en las últimas 2 horas. Si es el 2do caso, faltaría agregar un atributo a los partidos con la fecha de creación.

Si, son los partidos creados y jugadores anotados en las últimas 2 horas. Así que le hace falta una fecha de creación a los partidos para poder filtrarlos desde ahí.

> En el story 2 dice "Como usuario quiero anotarme a un partido ya creado ingresando mis datos de contacto (teléfono y mail)". Creo que se puede interpretar de dos formas:
Cada vez que uno se anota ingresa de nuevo los datos, y estos datos pueden cambiar entre partido y partido. 
O es único por usuario como está planteado ahora.

Yo creo que podríamos pedirlos cada vez que un usuario se anota, pero ir y pisarlos a la única referencia que se guarde de ese usuario. Me parece raro que un usuario quiera tener teléfono y email distinto por partido. Pero no estoy 100% seguro, habría que preguntar.

![imagen](https://user-images.githubusercontent.com/11778309/187197346-358f7c3a-8546-49b9-9059-512397718bfb.png)

> El playingFieldNumber es discutible, al menos yo creo que está de más. Estaríamos asumiendo que siempre hay un número de cancha y, si lo tuviera, también podría ser parte de location.

Coincido, para mi podes dejar texto libre en la `location` y si tiene número de cancha, que vaya ahí.

**Match**

- id
- name
- User ownerId (ID del creador del partido)
- date
- hour
- location
- creationDate
- startingPlayers
- substitutePlayers

**Player**

- User user (o sólo userId)
- LocalDateTime confirmationDate

**User**

- id
- alias
- fullName
- phone
- email
- password <- para mi esto no va. Entiendo que el user va a tener una Api Key que es como un acceso que se valida a nivel app, no a nivel usuario

**Comment by FranCICSo** [comment]
Hola @juan-nisimura ¿te parece hacer un builder de `Match`? Porque tiene muchos atributos, algunos como `creationDate` no haría falta pasárselo para instanciar uno, si no que lo pones en el build, al igual que el id puede generarlo el mismo builder y que puede ser un [UUID versión 4](https://www.uuidgenerator.net/dev-corner/java). Además podes validar que la fecha del partido no sea de ayer. De todos modos, sería después de crear los [POJO](https://es.wikipedia.org/wiki/Plain_Old_Java_Object) del dominio

**Comment by juan-nisimura** [comment]
Sí, creo que es buena idea. Ahora empiezo con todo esto y lo veo.
