### ISSUE TITLE
FE: La fecha muestra Invalid Date en la pantalla de matches

### ISSUE THREAD

**Issue by juan-nisimura** [leobz/organize-matches#85]
Foto:

https://prnt.sc/n5tE0sVxBpKf

**Comment by leobz** [comment]
No se pudo replicar el comportamiento

**Comment by leobz** [comment]
https://prnt.sc/n2wWjRaK8A4C

**Comment by leobz** [comment]
Nota: Se detecto que el siguiente formato -> new Date("2022-10-26T01:37z") con "z" al final no funciona en Firefox, pero si en Chrome
