### ISSUE TITLE
FE: No se muestra la fecha en la pantalla de editar partido

### ISSUE THREAD

**Issue by juan-nisimura** [leobz/organize-matches#86]
Foto:
https://prnt.sc/EEtsYGYHC76g

**Comment by leobz** [comment]
No se pudo replicar el comportamiento

**Comment by leobz** [comment]
Se detectó que era un problema del parseo del Date en el String, que tenia "z" miniscula al final, y se paso a "Z" (mayuscula).
Si bien este problema no se presentaba en Chrome, se prestentaba en Firefox, por loq ue con el nuevo cambio funciona en ambos navegadores.
