### ISSUE TITLE
Cloud: Subir imágenes a Dockerhub o AWS

### ISSUE THREAD

**Issue by juan-nisimura** [leobz/organize-matches#88]
- [x] Investigar si Dockerhub permite múltiples usuarios.
- [x] Crear cuenta compartida de docker hub
- [x] Hacer prueba de push y pull de imágenes.
- [x] Agregar comando en el makefile para automatizarlo.

**Comment by aleasquini** [comment]
Usuario creado en gmail para asociar Dockerhub:
user: organize.matches.tacs2022@gmail.com
pass: TACS2022
