### ISSUE TITLE
BUG: Optimizar Query de estadisticas

### ISSUE THREAD

**Issue by leobz** [leobz/organize-matches#93]
3-En este punto esperamos que esto no sea una simple Query a la base de datos

```
public CounterDTO getMatchAndPlayerCounterFrom(LocalDateTime from) {
    List<Match> matches = matchRepository.findByCreatedAtAfter(from);
    List<Player> players = playerRepository.findAll();
    logger.info("{} MATCHES AND {} PLAYERS CONFIRMED IN THE LAST TWO HOURS ", matches.size(), players.size());
    return new CounterDTO(matches.size(), players.size());
}
```
La idea de las estadísticas es que sean un dato precalculado y que no tenga que tirar una query pesada por cada vez que se ingresa al dashboard. Sugiero que usen un counter simple en Redis y si quieren ponerle onda pueden usar el concepto de sliding window. Les dejo un hilo de Stackoverflow que lo explican de lujo. Respuesta número 2.

https://stackoverflow.com/questions/8269916/what-is-sliding-window-algorithm-examples

**Comment by aleasquini** [comment]
**Se envía mail a ayudantes**

Hola Diego,

Nos juntamos con el equipo para repasar tus comentarios y tenemos una consulta sobre el punto 3.

La estrategia que utilizamos para guardar los Players dentro de MongoDB fue generar un índice que auto expira el documento cuando transcurren dos horas. Por lo tanto entendemos que, para este caso en particular, no es una query pesada siendo que todavía es mejorable utilizando un count() en vez de un findall(). 

La consulta entonces es:  Replicar este comportamiento para un repositorio especial de Matches (auto expirables al transcurrir las dos horas) y que soporte el requerimiento de "Partidos creados en las últimas dos horas"... ¿Consideras a esta estrategia como performante para realizar las estadísticas en tiempo real?




Gracias de antemano,
Saludos!
Ale

**Comment by aleasquini** [comment]
### **Estrategia utilizada:** 

Se crea nueva clase Stadistics con atributos:
 **StatisticType**: INT, 1 para matches, 2 para players
**confirmedAt**: Hora actual. Se le mapea un indice para expirar el documento post 2 horas.
**id**: idDocumento 

Al crearse un match, se crear un objeto Stadistic seteado en 1.
Al anotarse un player a un match, se crear un objeto Stadistic seteado en 2.

Se crea un método de tipo Count para 1.
Se crea un método de tipo Count para 2.

Se consultan ambos querys en **getMatchAndPlayerCounterFrom**.

**Comment by aleasquini** [comment]
https://github.com/leobz/organize-matches/commit/69e36ec1ca6b2e4b21ba5a15d121c53fc6394389
